version: '3.8'

services:
  bloom-server:
    build:
      context: ./Bloom_Filter_Server 
      dockerfile: Dockerfile
    ports:
      - "4000:4000"


  web-server:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    depends_on:
      - bloom-server

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/dockerfile
    ports:
      - "3000:80"
    depends_on:
      - web-server
