version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bloom_server
    stdin_open: true
    tty: true
    command: ["./bloom_filter_app", "1234", "256", "3", "2", "1"]
    networks:
      - appnet
    ports:
      - "1234:1234"  # Expose server port to host machine

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: bloom_client
    depends_on:
      - server
    stdin_open: true
    tty: true
    command: ["python", "Client.py", "bloom_server", "1234"]
    networks:
      - appnet
    # Adding this makes the client container wait for manual attachment
    entrypoint: ["tail", "-f", "/dev/null"]

networks:
  appnet: